### ISSUE TITLE
Badge not embedded despite `polar` label added on one particular repo

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#628] opened 2023-06-01 19:28 UTC
Specifically https://github.com/anthonycorletti/cloudrun-fastapi issue nr. 5. Not doing a direct link to avoid cluttering their timeline with this (not relevant).

**Comment by zegl** [comment] 2023-06-07 09:09
I'm unable to reproduce this. I've added more logs (in #629) to have more data to use if this happens again.

Closing this issue for now, let's re-open it if/when this happens again.

**Closed by zegl** 2023-06-07 09:09 UTC
Labels: bug
