### ISSUE TITLE
$20 default persists even when the user picks a larger value

### ISSUE THREAD

**Issue by Jeremiah-England** [polarsource/polar#1537] opened 2023-10-21 14:30 UTC
I tried to sponsor a couple issues for $50 and it says that I sponsored them for $20 still.

Steps to reproduce:

1. Paste an issue into the top of the feed to fund it: https://polar.sh/feed
2. Click "continue"
3. Change the amount in the input field with "20" to something larger.
4. Select your payment method and click "Fund this issue".
5. Look at your feed again. It will probably say you are funding the issue for $20.

**Comment by emilwidlund** [comment] 2023-10-21 14:42
@Jeremiah-England Interesting. How much were you charged for?

**Comment by Jeremiah-England** [comment] 2023-10-21 15:07
> @Jeremiah-England Interesting. How much were you charged for?

@emilwidlund I just checked my credit card and they came through as $20.

**Comment by birkjernstrom** [comment] 2023-10-21 16:29
Thank you @Jeremiah-England for both the pledges and the excellent bug report & apologies for it affecting you.

I'll take a look this evening 🙏

**Comment by birkjernstrom** [comment] 2023-10-21 21:43
Was able to reproduce. It took me a bit; I tried multiple browsers and flows without running into the issue at first. Until, I tried:
1. Authenticated w.o payment method on file (Unauthenticated is the same)
2. Changing price after the Stripe Payment form is rendered

Embarrassingly, that it took me so long to reproduce is because it was not a flow I do often. I either have a payment method on file or in unauthenticated (guest) checkout tests, I always change the price repeatedly, but not once the Stripe Payment form is rendered that often. Will work on fixing this ASAP and ship a fix tomorrow or Monday at the latest.

Thanks again @Jeremiah-England for sharing this bug, I really appreciate it! 🙏🏼

**Comment by emilwidlund** [comment] 2023-10-21 22:09
> Was able to reproduce. It took me a bit; I tried multiple browsers and flows without running into the issue at first. Until, I tried:
> 
> 1. Authenticated w.o payment method on file (Unauthenticated is the same)
> 2. Changing price after the Stripe Payment form is rendered
> 
> Embarrassingly, that it took me so long to reproduce is because it was not a flow I do often. I either have a payment method on file or in unauthenticated (guest) checkout tests, I always change the price repeatedly, but not once the Stripe Payment form is rendered that often. Will work on fixing this ASAP and ship a fix tomorrow or Monday at the latest.
> 
> Thanks again @Jeremiah-England for sharing this bug, I really appreciate it! 🙏🏼

Really curious to hear what caused it ☺️

**Comment by birkjernstrom** [comment] 2023-10-22 20:59
Fixed in https://github.com/polarsource/polar/pull/1538 – will deploy tomorrow AM since it's a bit late and don't want to risk running into any issues with midnight around the corner :) 

The issue came down to lack of proper dependency arrays in the `useCallback` hooks so they where only ran once with an empty array vs. upon changes to state updates they depended on.

**Comment by emilwidlund** [comment] 2023-10-22 21:03
> Fixed in https://github.com/polarsource/polar/pull/1538 – will deploy tomorrow AM since it's a bit late and don't want to risk running into any issues with midnight around the corner :) 
> 
> 
> 
> The issue came down to lack of proper dependency arrays in the `useCallback` hooks so they where only ran once with an empty array vs. upon changes to state updates they depended on.

Ahh, one of the most common React-related bugs 😄
Nice find 👍🏻

**Comment by birkjernstrom** [comment] 2023-10-22 21:08
> Ahh, one of the most common React-related bugs 😄

Yes, it's so easy to run into since you have to provide an empty array at first to avoid the infinite loop even before you've fully baked the function and at that point, you forget about it. I couldn't understand why the function seemingly always created a payment intent vs. updating it and realized the state was broken. Only then did I see my editor complain about the lack of dependencies in the array and it clicked :)

**Closed** 2023-10-23 09:19 UTC
