### ISSUE TITLE
Subscriber stats overflowing posts in dashboard

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2132] opened 2024-01-07 17:05 UTC
When reducing the width of the browser media queries kick in that shows subscribers on top and posts underneath.

However, it's actually placed on top visually (fixed) with posts being scrollable underneath.

We should reduce the size of the stats boxes in smaller screens and have them side-by-side without being fixed so you can see & scroll posts underneath

**Comment by emilwidlund** [comment] 2024-01-11 11:05
Can't reproduce this anymore. Closing for now.

**Closed by emilwidlund** 2024-01-11 11:05 UTC
