### ISSUE TITLE
Cannot delete organization

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#4728] opened 2024-12-23 14:31 UTC
### Description

I just created https://polar.sh/dashboard/python-icalendar
But I would like to delete it.

### Current Behavior

When I go to the settings of that organization, I see nothing to remove it.
https://polar.sh/dashboard/python-icalendar/settings

### Expected Behavior

When I go to the settings of that organization, I would expect a way to remove it.

### Screenshots

![grafik](https://github.com/user-attachments/assets/0f998d0a-e4ef-4c13-88a6-6e449a03f390)

### Environment:

-   Operating System: [e.g., Windows, macOS, Linux] Linux
-   Browser (if applicable): [e.g., Chrome, Firefox, Safari], Firefox

---

**Comment by birkjernstrom** [comment] 2024-12-23 19:36
Closing as duplicate of https://github.com/polarsource/polar/issues/4476

Reach out to me at support@polar.sh and I can help delete your account @niccokunzmann

**Closed by birkjernstrom** 2024-12-23 19:36 UTC
Labels: bug
